import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1 className="text-lg text-blue-500">Some header W w</h1>
        <p className="font-mont">
          Lorem ipsum dolor sit amet consectetur adipisicing elit. Pariatur,
          distinctio rem! Similique incidunt distinctio, vero beatae suscipit ab
          error autem delectus ullam unde repellendus quibusdam veritatis, porro
          fugiat quidem. Ut.
        </p>
      </main>
    </>
  );
}
